### ISSUE TITLE
Add tag button next to each search result

### ISSUE THREAD

**Issue by benye11** [ucsb-cs56-w20/mapache-search#129]
In search results, add button next to each result allowing user to search and add tags to a result.

Button behavior is up to your implementation, i.e. can be drop-down, etc.

This can be broken into several issues

- [x] button next to each link exists
- [x] button has a functional drop-down
- [x] drop-down shows the tags
- [x] drop-down also has search bar allowing searching for tags
- [x] user can select tag from drop-down
- [x] selecting tag will add specific tag to the link
- [x] database will store this link-tag association

**Comment by jay-red** [comment]
On /src/main/resources/templates/searchResults.html, we need to add preprocessing ${} statements for the HTML rendering to display a button for tagging a search query. This will need to interface with whatever backend functionality there is for creating tags. Ideally, this would not require the user to switch pages, and instead be something requested & rendered on the search results page. This will require JavaScript's XMLHttpRequest or a library which implements it, to asynchronously fetch tags, and a allow a user to update the tags or a query on the page.
